### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [velijoze/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by velijoze** [comment]
Thanks Mikeysax.  Added the mobile meta tag to my application.html.erb file and removed the absolute positioning of the footer from footer.css.scss in order to avoid overlapping text and footer on About page when viewed on mobile.

Zoran

**Comment by Mikeysax** [comment]
Nice job figuring it out :+1:
